


black_body='The absolute black body is the hypothetical body that absorbs the waves of all frequencies and emits waves of all frequencies'
spectrum='Different elements can emit waves of different frequencies. You might have come across an expression “the emission spectrum of an element”. This is what is used to determine the chen=mical composition of istant objects.This has to do with Balmer’s formula. Bohr derived Balmer’s formula with his atomic model. He mixed up classical and quantum physics and he got the same formula, but with R,Ridberg’s constant, represented as 2pi2nq4 /h3. This formula allowed to calculate the spectrum for hydrogen from the knowledge about the electrons on its orbits.'
thermonuclear_fusion='A process of synetesis of particles that happens in the bright stars due to high outward pressure and high gravity. This process can be recreatd on Earth in special facilities provided high enough temperature. This is usually achieved with plasma in magnetic confinement or intertial confinement with lasers.'
higgs_field='The Higgs field interacts only with the particles that have mass. The massless particles, such as photons would not interact with it and it passes quickly through it. The particles that have mass would interact with the Higgs Field, and hence with the Higgs bosons. Thus, they would get attracted to the mass particle and it would slow down the particle. Because of these interactions the particle is slower. And because it is slower, it has mass. (Massless neutrinos and photons travel at the speed of light (or almost that)). Mass comes from interactions with the field.'
quantum_entanglement='A pair of particles is entangled when the quantum state of each particle cannot be described independently of the quantum state of the other particle. The outcome of an individual measurement of the state of a particle is random, but he states of the two particles are correlated (regardless of the distance separating them).'
vector_field=''
pp_cycle='After this happens, a gas cloud becomes a star and begins to shine. Inside the stars, hydrogen atoms are fused together to make helium. The particles go through a pp-cycle (proton-proton cycle).'
cno_cycle='Another process that goes on in heavier stars (T of approximately 20 million Kelvin) is the CNO cycle. CNO stands for Carbon Nitrogen Oxygen. It is important to understand that the CNO cycle is the only way these particle are ever created.What happens is the nuclei of heavier elements undergo transformation due to individual protons fusing with them.The CNO cycle was first proposed by Hans Bethe. Legend says that Bethe solved the problem of energy production in stars on the train on the way home, instead of a crossword, on the way from the conference on this topic. The challenge was to find just the right reactions with energy output high enough to maintain the Sun’s energy output, but not high enough for the sun to self-disrupt.'                     
g_r_diagram='a scatter plot of stars showing the relationship between the stars absolute magnitudes or luminosities versus their stellar classifications or effective temperatures. The diagram was created independently around 1910 by Ejnar Hertzsprung and Henry Norris Russell, and represented a major step towards an understanding of stellar evolution.'
superposition=''
bohrs_principle='n Bohr’s model, an excited (with some additional energy) electron can only jump to an orbit, where its energy will change by a number divisible by h/2pi.  L=n(h/2pi) is the condition of existence of a quantum orbit. n here is the number of orbit. So, the impulse of an electron on the nearest orbit to the nucleus will have moment of impulse of L=1(h/2pi), the second one – L=2(h/2pi). This number is so important that there is even a special notation for h/2pi. It is just used so often. It is also worth remembering that h/2pi is actually a very specific number, a constant. It is not a variable. '
st_model='Today’s prime convention in particle physics is the standard model. The particles are generally divided into two categories: the leptons and the quarks. The leptons are those light particles like the electrons and its heavier alike types:  tau and muon. They come alongside their neutrinos. Back in September, I made a talk about neutrinos. Now you can see where they are in the standard model and what they are actually doing there. Notice, that neither protons, nor neutrons are here. This is because they are not elementary particles. They consist of quarks. This is called quark confinement. '
bosons=''
fermions=''
quarks=''
qubit='Qubits are made using physical systems, such as the spin of an electron or the orientation of a photon. These systems can be in many different arrangements all at once, a property known as quantum superposition. Qubits can also be inextricably linked together using a phenomenon called quantum entanglement.'
newton_laws1='An object will remain at rest or continue to move with constant velocity unless acted upon by a resultant force'
newton_laws2='Force is equal to the rate of change of momentum'
newton_laws3='When two objects interact, they exert equal and opposite forces on each other'
gravity='The force of attraction of all objects to oher o jects with mass. Most notable with the attraction of smaller bodies to large bodies of astronomical scale.'
qed='In QED, in a field the electrons exchange virtual photons. Sound difficult, but it is really not. You see, what we should find in a field is energy. In QED, energy can be represented as particles exchanging photons. An electron randomly emits a photon, and another electron absorbs it. Thus, the first electron has less energy and the second one – more. But this is only briefly, because at the next fraction of a second some different photon would pass on an electron to it.'
pe_effect='Photoelectric effect can be described by this formula: qU0 = hf-P ; qU0=E(max); E (max) = ½ m(e)v**2 (qU0 is the energy needed to neutralize the kinetic energy and turn the stream of electrons into zero, this comes from method by which the energy of electrons is measured.   ‘q’ is the charge of electon and U is the voltage needed to hold it.'
quants="Small packets of energy. One packet of energy is a multiple of h, which is Planck's constant and is equal to 6.63*10^-34."
big_bang='The event 13.8 billion years ago that is cconsidered to be the beginning of the Universe. At he Big Bang, there existed a singularity that had an infinitely small volume and an infinitelybig mass beacuse of an infinte density. That singularity contained all the particles that the Universe consists of. At the Big Bang, the singularity suddenly started to expand. Once the particles populated the rapidly expanding Universe, some of them started to merge and interact with each other due to differences in charge. '
feynman_diagrams='Represenation of complicated interactions in quantumm electrodynamics in the form of lines and arrows that represent a sequence of following events: These three events are: /n 1.	 Photon moves from one location to the other /n 2.	 Electron moves from one location to the other/n 3.	 Electron emits a photon or absorbs a photon'

